### ISSUE TITLE
bug: hide-create-button patch causes startup crash

### ISSUE THREAD

**Issue by old4error** [revanced/revanced-integrations#178]
### Type

Other

### Bug description

hide create button causes crash at startup. tested and confirmed in log

### Steps to reproduce

also I used cli 2.14.0, patches 2.85 and integrations 0.54.0. also I use evolutionx rom 7.2 android 13, 20 oct build, device: poco x3 pro
1. start building revanced as usual
2. include hide-create-button patch
3. expect crash after building and mounting

### Relevant log output

```shell
time: 1666292481733
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
stacktrace: arjx: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at arle.a(PG:2)
	at armd.b(PG:3)
	at armd.tl(PG:5)
	at arzw.tl(PG:5)
	at asby.run(PG:4)
	at aeaq.run(PG:2)
	at ashm.run(PG:2)
	at asho.run(PG:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at app.revanced.integrations.patches.HideCreateButtonPatch.hideCreateButton(HideCreateButtonPatch.java:38)
	at kzw.z(PG:31)
	at kyt.a(PG:45)
	at armd.tl(PG:2)
	... 13 more
```

### Solution

exclude hide-create-button from patch list while building.

### Additional context

btw, I tried to patch revanced on android_x86 (blissos 11.14) vm and suddenly it works even with this patch

**Comment by old4error** [comment]
where tf did it find line 38 in HideCreateButtonPatch.java?
https://github.com/revanced/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/patches/HideCreateButtonPatch.java

**Comment by Canny1913** [comment]
> where tf did it find line 38 in HideCreateButtonPatch.java? https://github.com/revanced/revanced-integrations/blob/main/app/src/main/java/app/revanced/integrations/patches/HideCreateButtonPatch.java

line 38 in compiled java code, not source code.

**Comment by oSumAtrIX** [comment]
Are you patching a compatible version of the app?

**Comment by oSumAtrIX** [comment]
Also which patches version was the last time it worked?
