### ISSUE TITLE
Premium heading patch fails with FileNotFound exception

### ISSUE THREAD

**Issue by pieterhouwen** [revanced/revanced-integrations#18]
I think it looks for an image that's supposed to be at: https://github.com/revanced/revanced-integrations/tree/main/app/src/main/res/drawable-xxxhdpi

```
app.revanced.patcher.patch.implementation.misc.PatchResultError: revanced-cache\res\drawable-xxxhdpi\yt_premium_wordmark_header_light.png
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264)
        at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282)
        at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:58)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:106)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.nio.file.NoSuchFileException: revanced-cache\res\drawable-xxxhdpi\yt_premium_wordmark_header_light.png
```

**Comment by TheJeterLP** [comment]
You have to use the .jar file, not the .dex file. That's why it doesn't work.

**Comment by pieterhouwen** [comment]
Ah alright, so for -m I have to use the .apk file from https://github.com/revanced/revanced-integrations/releases/tag/v0.11.0 ?

Because the help menu asks for a .dex file for the -m switch

**Comment by TheJeterLP** [comment]
Use the APK with -m. And read docs.

Mit freundlichen Grüßen
Joey Peter

pieterhouwen ***@***.***> schrieb am Mi., 22. Juni 2022,
12:51:

**Comment by daBroma** [comment]
Reading docs is quite hard eh?

**Comment by pieterhouwen** [comment]
> With -m there can be a dex file or a jar
Maybe I'm really simple minded but an .apk file does not look like a .dex or a .jar file

You know... Because of the extension.

**Comment by pieterhouwen** [comment]
However you guys have a solid point in calling me a dumbass so I will admit defeat and wish you all a great day

**Comment by pieterhouwen** [comment]
```
D:\Downloads\revanced>java -jar revanced-cli-1.7.0-all.jar -a YouTube_base.apk -c -d E977XB2ZM08213714 -o revanced.apk -m app-release-unsigned.apk -b revanced-patches-1.9.1.jar
``` 

Still throws the same error btw

**Comment by pieterhouwen** [comment]
```
java -jar revanced-cli-1.7.1-all.jar -a YouTube_base.apk -c -d E977XB2ZM08213714 -o revanced.apk -m app-release-unsigned.apk -b revanced-patches-1.9.1.jar
```

No luck, still same error

**Comment by NoodleSoup** [comment]
Remove the cache folder if you have that and make sure it's the full apk not a split YouTube apk.

**Comment by Sculas** [comment]
Oh, you should use the full APK, not base. This only works on nonroot though, since the Patcher does not have split support yet. Disable the premium-heading patch if building for root.

**Comment by pieterhouwen** [comment]
Ah that makes sense :) Any ideas on how I can get the full YT apk? I'm using an app called APK Extractor on my phone so I don't have to use shady APK sharing sites

**Comment by pieterhouwen** [comment]
Thanks! Now it proceeds alot longer before unfortunately dying:

```
[aligning & signing]
[deploying]
se.vidstige.jadb.JadbException: command failed: device offline
        at se.vidstige.jadb.Transport.verifyResponse(Transport.java:43)
        at se.vidstige.jadb.JadbDevice.send(JadbDevice.java:237)
        at se.vidstige.jadb.JadbDevice.getTransport(JadbDevice.java:65)
        at se.vidstige.jadb.JadbDevice.push(JadbDevice.java:203)
        at se.vidstige.jadb.JadbDevice.push(JadbDevice.java:216)
        at se.vidstige.jadb.managers.PackageManager.install(PackageManager.java:53)
        at se.vidstige.jadb.managers.PackageManager.install(PackageManager.java:65)
        at app.revanced.utils.adb.Adb.deploy$revanced_cli(Adb.kt:32)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:123)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

adb is now offline on my phone

**Comment by NoodleSoup** [comment]
apk is there just transfer that or reconnect your phone and use adb install revanced.apk

**Comment by Sculas** [comment]
1. This is not a ReVanced issue. Something is wrong with your ADB setup.
2. Please don't reuse this issue for other issues.

**Comment by TheJeterLP** [comment]
That seems to be an issue with your phone or adb drivers.

pieterhouwen ***@***.***> schrieb am Mi., 22. Juni 2022,
13:31:
