### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.util.jar.JarEntry.g etRealName()Ljava/lang/String;

### ISSUE THREAD

**Issue by Phongvngg1** [revanced/revanced-integrations#26]
This is my full log:
C:\Users\admin\Downloads\Extract&Run>java -jar revanced-cli-all.jar -a yt.apk -c
  -o revanced.apk -b revanced-patches.jar -m app-release-unsigned.apk --experime
ntal
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging app-release-unsigned.apk
Exception in thread "main" java.lang.NoSuchMethodError: java.util.jar.JarEntry.g
etRealName()Ljava/lang/String;
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle$loadPat
ches$2.invoke(JarPatchBundle.kt:27)
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle$loadPat
ches$2.invoke(JarPatchBundle.kt:13)
        at app.revanced.patcher.util.patch.util.StringIterator.next(StringIterat
or.kt:9)
        at app.revanced.patcher.util.patch.util.StringIterator.next(StringIterat
or.kt:3)
        at app.revanced.patcher.util.patch.base.PatchBundle.loadPatches$revanced
_patcher(PatchBundle.kt:19)
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle.loadPat
ches(JarPatchBundle.kt:13)
        at app.revanced.utils.patcher.PatcherKt.addPatchesFiltered(Patcher.kt:22
)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:122)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSame
Parent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.ja
va:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

C:\Users\admin\Downloads\Extract&Run>java -jar revanced-cli-all.jar -a yt.apk -c
  -o revanced.apk -b revanced-patches.jar -m app-release-unsigned.apk --experime
ntal
INFO: Decoding resources
INFO: Reading dex files
INFO: Merging app-release-unsigned.apk
Exception in thread "main" java.lang.NoSuchMethodError: java.util.jar.JarEntry.g
etRealName()Ljava/lang/String;
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle$loadPat
ches$2.invoke(JarPatchBundle.kt:27)
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle$loadPat
ches$2.invoke(JarPatchBundle.kt:13)
        at app.revanced.patcher.util.patch.util.StringIterator.next(StringIterat
or.kt:9)
        at app.revanced.patcher.util.patch.util.StringIterator.next(StringIterat
or.kt:3)
        at app.revanced.patcher.util.patch.base.PatchBundle.loadPatches$revanced
_patcher(PatchBundle.kt:19)
        at app.revanced.patcher.util.patch.implementation.JarPatchBundle.loadPat
ches(JarPatchBundle.kt:13)
        at app.revanced.utils.patcher.PatcherKt.addPatchesFiltered(Patcher.kt:22
)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:122)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSame
Parent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.ja
va:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

Image: https://i.imgur.com/4ivDAvz.png

**Comment by Itroublve** [comment]
You need Zulu JDK 17 (a java distribution) for it to work properly. To check Java version `java --version`

**Comment by TheJeterLP** [comment]
As said, wrong JDK used
