### ISSUE TITLE
Latest integrations update freezes the play/pause button

### ISSUE THREAD

**Issue by TheSynt4x** [revanced/revanced-integrations#28]
I tried patching it with the latest integrations (v0.17.0) and latest patches (2.0.2). This resulted in the pause button being frozen and me not being able to tap out of it. Impossible to watch videos on fullscreen. Reverting back to 2.0.1 patches and 0.15.0 integrations seemed to fix the issue. I'm not sure whether the issue is in integrations or if it's in the patches, but I would assume it has to do with the refactoring made to some parts of the code. Bugs, amirite?

**Comment by TheSynt4x** [comment]
Running latest integrations (v0.17.0) with 2.0.1 patches results in the following:

```
app.revanced.patcher.patch.PatchResultError: seekbar-tapping depends on integrations but the following error was raised: Integrations have not been merged yet. This patch can not succeed without the integrations.
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:268)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:43)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:307)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:94)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:122)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

I'm sorry, I may be doing something wrong. I'll try to run latest integrations with latest patches.

**Comment by oSumAtrIX** [comment]
Thanks, it is indeed a bug, use the last release until fixed.

**Comment by TheJeterLP** [comment]
Latest Integrations have obviously need to be used with the latest patches :)
