### ISSUE TITLE
bug: SwipeHelper fails to retrieve user stats in SponsorBlock on YouTube ReVanced

### ISSUE THREAD

**Issue by kennychenfs** [revanced/revanced-integrations#340]
### Type

Other

### Bug description

When accessing the SponsorBlock feature in YouTube ReVanced on my Pixel 4a 5G device, the following error message appears: "SwipeHelper: failed to retrieve user stats". I noticed in the log that the SwipeHelper module is fetching information from some url like 
https://sponsor.ajay.app/api//api/userInfo?userID=xxxxxxxxxxxxxxx&values=["userName", "minutesSaved", "segmentCount", "viewCount"]

### Steps to reproduce

Reproduce Steps:

1. Navigate to Settings/SponsorBlock.
2. The error message "SwipeHelper: failed to retrieve user stats" appears.

Device and software details:

- Device: Pixel 4a 5G
- Android version: T3B1.230224.005
- Patches version: 2.166.0
- Integrations version: 0.100.1
- CLI version: 2.20.1

I built it on Ubuntu 22.04 with java-11-openjdk-amd64.

Additional information:

The bug has been present for a long time and may exist in older versions of YouTube ReVanced.

### Relevant log output

```shell
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: failed to retrieve user stats
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: java.io.FileNotFoundException: https://sponsor.ajay.app/api//api/userInfo?userID=xxxxxxxxxxxxxxx&values=["userName", "minutesSaved", "segmentCount", "viewCount"]
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at app.revanced.integrations.requests.Requester.parseJson(Requester.java:1)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at app.revanced.integrations.requests.Requester.parseJSONObject(Requester.java:3)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at app.revanced.integrations.requests.Requester.parseJSONObjectAndDisconnect(Requester.java:1)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at app.revanced.integrations.sponsorblock.requests.SBRequester.getJSONObject(SBRequester.java:5)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at app.revanced.integrations.sponsorblock.requests.SBRequester.lambda$retrieveUserStats$8(SBRequester.java:15)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at app.revanced.integrations.sponsorblock.requests.SBRequester.$r8$lambda$R5Lq084FjQUHgLTrhNheKrExJno(Unknown Source:0)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at app.revanced.integrations.sponsorblock.requests.SBRequester$$ExternalSyntheticLambda3.run(Unknown Source:4)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-24 20:29:05.794 17796 18101 E revanced: SwipeHelper: 	at java.lang.Thread.run(Thread.java:1012)
```

### Solution

fix the url

**Comment by kennychenfs** [comment]
Yes, changing the API server address works.
