### ISSUE TITLE
bug: YT immediately crashing

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-integrations#551]
### Bug description

After patching, YT immediately crashing.
Patch with cli
```
java -jar revanced-cli-4.4.0-all.jar patch -r "revanced-cache" -p -o Install\YouTube_18.45.43_ReVanced.apk --options options.json -b revanced-patches-4.0.0-dev.6.jar --alias=<redacted> --keystore-password=<redacted> --keystore-entry-password=<redacted> --keystore=my-own.keystore -m revanced-integrations-1.1.1-dev.5.apk Apps\com.google.android.youtube-18.45.43-all.apk -i "Change header"
```

### Error logs

```shell
--------- beginning of crash
01-10 14:34:02.931 23155 23155 E AndroidRuntime: FATAL EXCEPTION: main
01-10 14:34:02.931 23155 23155 E AndroidRuntime: Process: app.revanced.android.youtube, PID: 23155
01-10 14:34:02.931 23155 23155 E AndroidRuntime: java.lang.RuntimeException: java.lang.NoSuchMethodError: No static method onLithoTextLoaded(Ljava/lang/Object;Ljava/lang/CharSequence;)Ljava/lang/CharSequence; in class Lapp/revanced/integrations/youtube/patches/ReturnYouTubeDislikePatch; or its super classes (declaration of 'app.revanced.integrations.youtube.patches.ReturnYouTubeDislikePatch' appears in /data/app/app.revanced.android.youtube-GVS9ZoKI5krVuTunSsim9w==/base.apk!classes5.dex)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at ewx.a(PG:64)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.facebook.litho.ComponentTree.m(PG:15)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.facebook.litho.ComponentTree.N(PG:15)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.facebook.litho.ComponentTree.q(PG:8)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at ezk.onMeasure(PG:25)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.measure(View.java:25161)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at on.bv(PG:12)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.B(PG:11)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.J(PG:7)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.n(PG:98)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.libraries.youtube.rendering.ui.ScrollToTopLinearLayoutManager.n(PG:1)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.aS(PG:9)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.F(PG:9)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(PG:1)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(PG:9)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at ahyd.vx(PG:19)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at ahyf.rG(PG:1)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.rG(PG:1)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.apps.youtube.app.ui.actionbar.MainScrollingViewBehavior.rG(PG:1)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:6)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchContainerLayout.g(PG:2)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchContainerLayout.h(PG:7)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.apps.youtube.app.watch.nextgenwatch.ui.NextGenWatchContainerLayout.onLayout(PG:4)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.apps.youtube.app.common.ui.navigationbar.NavigationBarDividerLayout.onLayout(PG:4)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at com.google.android.apps.youtube.app.ui.swipetocontainer.SwipeToContainerFrameLayout.onLayout(PG:1)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at bjo.onLayout(PG:6)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-10 14:34:02.931 23155 23155 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1146)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.View.layout(View.java:22496)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:911)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No static method onLithoTextLoaded(Ljava/lang/Object;Ljava/lang/CharSequence;)Ljava/lang/CharSequence; in class Lapp/revanced/integrations/youtube/patches/ReturnYouTubeDislikePatch; or its super classes (declaration of 'app.revanced.integrations.youtube.patches.ReturnYouTubeDislikePatch' appears in /data/app/app.revanced.android.youtube-GVS9ZoKI5krVuTunSsim9w==/base.apk!classes5.dex)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at a.W(PG:1)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	at ewx.a(PG:13)
01-10 14:34:02.932 23155 23155 E AndroidRuntime: 	... 91 more
```

### Additional context

YT 18.45.43
Android 10, ARMv8
Default patches

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-integrations/blob/dev/app/src/main/java/app/revanced/integrations/youtube/patches/ReturnYouTubeDislikePatch.java#L204
